name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. ดึง source code จาก GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. ติดตั้ง Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"
          channel: stable
          cache: true

      # 3. ตรวจสอบ Flutter
      - name: Flutter doctor
        run: flutter doctor

      # 4. ดึง dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 5. Build APK (Release)
      - name: Build APK
        run: flutter build apk --release

        - name: List APK files
          run: ls -R build/app/outputs

      # 6. เก็บไฟล์ APK เป็น Artifact
      - name: Upload APK 
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

